version: "3"
services:
  postgres:
    image: postgres:16-alpine
    env_file: ./.env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
      - postgres:/var/lib/postgres/data

  redis:
    image: redis:7-alpine
    env_file: ./.env
    command: "redis-server --requirepass ${REDIS_PASSWORD} --maxmemory ${REDIS_MAXMEMORY} --maxmemory-policy ${REDIS_MAXMEMORY_POLICY}"
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  api:
    build:
      context: ../../
      dockerfile: ./envs/dev/api.Dockerfile
    env_file: ./.env
    depends_on:
      - postgres
      - redis
      - worker
    links:
      - postgres:postgres
      - redis:redis
      - worker:worker
    ports:
      - "127.0.0.1:1111:1111"
      - "127.0.0.1:1113:1113"
    volumes:
      - ../../:/app

  worker:
    build:
      context: ../../
      dockerfile: ./envs/dev/worker.Dockerfile
    env_file: ./.env
    depends_on:
      - postgres
      - redis
    links:
      - postgres:postgres
      - redis:redis
    ports:
      - "127.0.0.1:1112:1112"
    volumes:
      - ../../:/app

  cli:
    build:
      context: ../../
      dockerfile: ./envs/dev/cli.Dockerfile
    env_file: ./.env
    depends_on:
      - postgres
      - redis
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - ../../:/app

  pgadmin:
    image: neoxelox/pgadmin4:latest
    profiles:
      - extra
    env_file: ./.env
    depends_on:
      - postgres
    links:
      - postgres:postgres
    ports:
      - "127.0.0.1:5433:80"
    volumes:
      - ./pgadmin4.json:/pgadmin4/config.json
      - pgadmin:/root/.pgadmin

  redisinsight:
    image: oblakstudio/redisinsight:2.3
    profiles:
      - extra
    env_file: ./.env
    depends_on:
      - redis
    links:
      - redis:redis
    ports:
      - "127.0.0.1:6380:5000"
    volumes:
      - redisinsight:/db

volumes:
  postgres:
  pgadmin:
  redis:
  redisinsight:
