#!/bin/bash

psql -U ${POSTGRES_USER} <<-END

CREATE USER ${SERVICE_DATABASE_USER} WITH
    CREATEROLE
    SUPERUSER
    PASSWORD '${SERVICE_DATABASE_PASSWORD}';

CREATE DATABASE ${SERVICE_DATABASE_NAME} WITH
    OWNER = ${SERVICE_DATABASE_USER};

CREATE DATABASE ${SERVICE_DATABASE_NAME}_TEST WITH
    OWNER = ${SERVICE_DATABASE_USER};

CREATE USER ${SERVICE_DATABASE_READONLY_USER} WITH
    PASSWORD '${SERVICE_DATABASE_READONLY_PASSWORD}';

GRANT CONNECT ON DATABASE ${SERVICE_DATABASE_NAME} TO ${SERVICE_DATABASE_READONLY_USER};

GRANT USAGE ON SCHEMA public TO ${SERVICE_DATABASE_READONLY_USER};

ALTER DEFAULT PRIVILEGES FOR USER ${SERVICE_DATABASE_USER} IN SCHEMA public
GRANT SELECT ON TABLES TO ${SERVICE_DATABASE_READONLY_USER};

END