name: Integration

on:
  pull_request:
    branches: [main]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Go 🐻
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: true

      - name: Setup Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Setup Scripts 🧩
        run: |
          pip install -r scripts/requirements.txt
          inv env.switch ci
          inv tool.install ci-int --yes

      - name: Lint 🪶
        run: inv lint

      - name: Start Infrastructure 👟
        run: inv start --detach

      - name: Test 🧪
        run: inv test
